In [50]:
import pandas as pd
import numpy as np

In [51]:
!ls

county_neighbors_1.csv	Untitled.ipynb


In [52]:
cn1 = pd.read_csv('county_neighbors_1.csv')

In [53]:
cn1

County        N1         N2         N3            N4        N5  \
0    Anderson  Cherokee  Freestone  Henderson       Houston      Leon   
1     Andrews       Lea      Ector     Gaines        Martin   Midland   
2    Angelina  Cherokee    Houston     Jasper   Nacogdoches      Polk   
3     Aransas   Calhoun     Nueces    Refugio  San Patricio       NaN   
4      Archer    Baylor       Clay       Jack  Throckmorton   Wichita   
..        ...       ...        ...        ...           ...       ...   
219      Wood      Camp   Franklin    Hopkins         Rains     Smith   
220    Yoakum       Lea    Cochran     Gaines       Hockley     Terry   
221     Young    Archer     Baylor       Jack    Palo Pinto  Stephens   
222    Zapata  Jim Hogg      Starr       Webb           NaN       NaN   
223    Zavala    Dimmit       Frio     Kinney      Maverick    Medina   

                N6        N7     N8   N9  
0              NaN       NaN    NaN  NaN  
1          Winkler       NaN    NaN  NaN  
2    San Augustine   Trinity  Tyler  NaN  
3              NaN       NaN    NaN  NaN  
4        Wilbarger     Young    NaN  NaN  
..             ...       ...    ...  ...  
219         Upshur  VanZandt    NaN  NaN  
220            NaN       NaN    NaN  NaN  
221   Throckmorton       NaN    NaN  NaN  
222            NaN       NaN    NaN  NaN  
223         Uvalde       NaN    NaN  NaN  

[224 rows x 10 columns]

In [54]:
s = len(cn1)

In [55]:
cn2 = np.zeros((s,s))

In [56]:
cn2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
np.fill_diagonal(cn2, 0.5)

In [58]:
cn2

array([[0.5, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.5, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.5, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.5, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.5]])

In [82]:
for x in range(s):
    
    r = np.sum(pd.notnull(cn1.iloc[x])) - 1
    
    for y in range(1, 9):
    
        c = cn1.iloc[x,y]
        
        for z in range(s):
            
            d = cn1.iloc[z,0]
            #print(z)
            #print(d)
            
            if (c==d):
            
                print(x)
                print(z)
                print(d)
                cn2[x,z] = 0.5/r

0
33
Cherokee
0
72
Freestone
0
96
Henderson
0
102
Houston
0
128
Leon
1
60
Ector
1
74
Gaines
1
139
Martin
1
145
Midland
1
217
Winkler
2
33
Cherokee
2
102
Houston
2
108
Jasper
2
153
Nacogdoches
2
165
Polk
2
180
San Augustine
2
199
Trinity
2
200
Tyler
3
25
Calhoun
3
157
Nueces
3
174
Refugio
3
182
San Patricio
4
10
Baylor
4
35
Clay
4
106
Jack
4
212
Wichita
4
213
Wilbarger
4
221
Young
5
13
Bexar
5
73
Frio
5
114
Karnes
5
125
La Salle
5
131
Live Oak
5
143
Medina
5
216
Wilson
6
40
Colorado
6
67
Fayette
6
70
Fort Bend
6
206
Waller
6
208
Washington
6
210
Wharton
7
36
Cochran
7
99
Hockley
7
123
Lamb
7
163
Parmer
8
13
Bexar
8
116
Kendall
8
117
Kerr
8
143
Medina
8
171
Real
8
203
Uvalde
9
24
Caldwell
9
67
Fayette
9
127
Lee
9
198
Travis
9
215
Williamson
10
4
Archer
10
94
Haskell
10
121
Knox
10
212
Wichita
10
213
Wilbarger
10
221
Young
11
78
Goliad
11
114
Karnes
11
131
Live Oak
11
174
Refugio
11
182
San Patricio
12
23
Burnet
12
45
Coryell
12
65
Falls
12
124
Lampasas
12
136
McLennan
12
146
Milam
12
215

121
10
Baylor
121
94
Haskell
122
53
Delta
122
66
Fannin
122
172
Red River
123
7
Bailey
123
31
Castro
123
36
Cochran
123
85
Hale
123
99
Hockley
123
133
Lubbock
123
163
Parmer
124
12
Bell
124
23
Burnet
124
45
Coryell
124
87
Hamilton
124
147
Mills
124
183
San Saba
125
5
Atascosa
125
56
Dimmit
125
58
Duval
125
73
Frio
125
209
Webb
126
40
Colorado
126
55
DeWitt
126
67
Fayette
126
79
Gonzales
126
107
Jackson
126
204
Victoria
127
9
Bastrop
127
22
Burleson
127
67
Fayette
127
146
Milam
127
208
Washington
127
215
Williamson
128
0
Anderson
128
18
Brazos
128
72
Freestone
128
102
Houston
128
130
Limestone
128
137
Madison
128
175
Robertson
129
32
Chambers
129
90
Hardin
129
91
Harris
129
109
Jefferson
129
150
Montgomery
129
165
Polk
129
181
San Jacinto
130
65
Falls
130
72
Freestone
130
98
Hill
130
128
Leon
130
136
McLennan
130
154
Navarro
130
175
Robertson
131
5
Atascosa
131
11
Bee
131
58
Duval
131
111
Jim Wells
131
114
Karnes
131
182
San Patricio
132
14
Blanco
132
23
Burnet
132
77
Gillespie
132
140


In [83]:
cn2

array([[0.5, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.5, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.5, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.5, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.5, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.5]])

In [84]:
cn2[0,33]

0.1

In [85]:
cn2[1,145]

0.08333333333333333

In [122]:
r1 = pd.read_csv('rank.csv')

In [123]:
r1

County      Rank
0    Anderson  0.000000
1     Andrews  0.000000
2    Angelina  0.071278
3     Aransas  0.083750
4      Archer  0.000000
..        ...       ...
219      Wood  0.000000
220    Yoakum  0.000000
221     Young  0.014597
222    Zapata  0.000000
223    Zavala  0.000000

[224 rows x 2 columns]

In [124]:
r1.iloc[:,1]

0      0.000000
1      0.000000
2      0.071278
3      0.083750
4      0.000000
         ...   
219    0.000000
220    0.000000
221    0.014597
222    0.000000
223    0.000000
Name: Rank, Length: 224, dtype: float64

In [125]:
rank = np.array(r1.iloc[:,1])

In [126]:
rank

array([0.        , 0.        , 0.07127807, 0.08375002, 0.        ,
       0.02534811, 0.03356464, 0.        , 0.        , 0.06979554,
       0.        , 0.        , 0.46964906, 1.60970135, 0.01222094,
       0.        , 0.07191791, 0.34904194, 0.65418546, 0.        ,
       0.        , 0.03657788, 0.01878098, 0.02657037, 0.03758971,
       0.05342371, 0.        , 0.37523167, 0.        , 0.        ,
       0.0271277 , 0.03215047, 0.06477654, 0.02329746, 0.        ,
       0.        , 0.        , 0.        , 1.05046795, 0.        ,
       0.        , 0.54258706, 0.        , 0.        , 0.        ,
       0.03287939, 0.00812191, 0.        , 0.        , 0.        ,
       4.29843492, 0.01519668, 0.01580725, 0.        , 1.10768497,
       0.        , 0.        , 0.        , 0.        , 0.02605057,
       0.08013312, 0.        , 0.63031618, 0.32284519, 0.01897569,
       0.01946124, 0.02195098, 0.01995847, 0.        , 0.        ,
       0.84245707, 0.03668988, 0.        , 0.        , 0.00892

In [127]:
rank.shape

(224,)

In [128]:
cn2.shape

(224, 224)

In [129]:
rank2 = np.dot(cn2, rank)

In [130]:
rank2

array([3.52445350e-03, 5.19822262e-02, 4.09503430e-02, 9.84170846e-02,
       2.76551006e-02, 1.18379913e-01, 1.04776036e-01, 8.19757258e-03,
       1.42476314e-01, 2.13206131e-01, 2.41982131e-02, 6.68842390e-03,
       2.71685705e-01, 8.65434326e-01, 1.62354787e-01, 4.04385558e-02,
       4.22423989e-02, 6.73155096e-01, 3.40926899e-01, 0.00000000e+00,
       3.04003906e-02, 2.01496966e-02, 8.69584692e-02, 1.73573078e-01,
       1.68020943e-01, 4.48998635e-02, 1.48156863e-02, 2.81625323e-01,
       1.32490758e-02, 1.35173315e-02, 2.55830074e-02, 3.17617852e-02,
       5.82314492e-01, 4.95175223e-02, 0.00000000e+00, 5.45501750e-02,
       8.87033121e-03, 1.26448059e-02, 1.02108798e+00, 0.00000000e+00,
       1.28491567e-02, 4.76905210e-01, 8.16041370e-03, 4.19017708e-03,
       1.24264399e-01, 6.47728319e-02, 1.20742649e-02, 4.51216944e-04,
       3.85799844e-02, 1.84030840e-03, 2.57283719e+00, 2.68992108e-02,
       2.43339614e-02, 1.31334244e-02, 1.16484973e+00, 1.21085389e-02,
      

In [131]:
rank3 = np.dot(cn2, rank2)

In [132]:
rank3

array([2.15344491e-02, 6.07695403e-02, 3.66588643e-02, 9.02169312e-02,
       3.58814334e-02, 1.38533343e-01, 1.71155066e-01, 1.74283627e-02,
       1.76742316e-01, 2.39459328e-01, 2.76535077e-02, 1.51379913e-02,
       1.96502827e-01, 5.45634513e-01, 2.18811670e-01, 7.42045520e-02,
       2.69540672e-02, 7.13438889e-01, 2.12270661e-01, 7.25170089e-05,
       4.63992607e-02, 1.51515128e-02, 1.07799863e-01, 2.00824077e-01,
       2.15914591e-01, 4.75241053e-02, 1.70406340e-02, 2.28723958e-01,
       2.45685298e-02, 1.54504723e-02, 2.19843820e-02, 3.62839156e-02,
       7.05676524e-01, 5.78128947e-02, 1.18667925e-04, 6.43785832e-02,
       2.00487676e-02, 1.59328056e-02, 9.31152788e-01, 0.00000000e+00,
       3.60501937e-02, 4.22069870e-01, 1.05628949e-02, 7.51693644e-03,
       2.28824044e-01, 7.39743685e-02, 1.75399694e-02, 4.75643390e-03,
       5.08242587e-02, 2.67572525e-03, 1.77112083e+00, 3.62379172e-02,
       2.37851355e-02, 3.16224032e-02, 1.05509134e+00, 1.73235819e-02,
      

In [136]:
r1.iloc[:,1] = rank3

In [137]:
r1

County      Rank
0    Anderson  0.021534
1     Andrews  0.060770
2    Angelina  0.036659
3     Aransas  0.090217
4      Archer  0.035881
..        ...       ...
219      Wood  0.043863
220    Yoakum  0.020270
221     Young  0.010287
222    Zapata  0.069174
223    Zavala  0.061238

[224 rows x 2 columns]

In [138]:
r1.to_csv(r'rankings.csv', index = False)